import type { ProcessSummary, ProductionProcess, ProductionStep, StepResource, StepResourceInput } from '../types/production.types'

export function calculateResourceTotal(quantity: number, unitCost: number): number { return Math.round(quantity * unitCost * 100) / 100 }
export function getAvailabilityStatus(quantity: number, availableStock: number) { if (availableStock <= 0) return 'Unavailable' as const; if (availableStock < quantity) return 'ToOrder' as const; if (availableStock <= quantity * 1.2) return 'LowStock' as const; return 'Available' as const }
export function createResource(input: StepResourceInput, stepId: string): StepResource { return { ...input, id: `res-${crypto.randomUUID()}`, stepId, totalCost: calculateResourceTotal(input.plannedQuantity, input.unitCost), availabilityStatus: getAvailabilityStatus(input.plannedQuantity, input.availableStock) } }
export function calculateStepPlannedCost(step: ProductionStep): number { const resources = step.resources.reduce((sum, resource) => sum + resource.totalCost, 0); return Math.round((resources + step.laborCost + step.plannedCost) * 100) / 100 }
export function calculateProcessSummary(process: ProductionProcess): ProcessSummary { return process.steps.filter((step) => step.status !== 'Inactive').reduce<ProcessSummary>((summary, step) => ({ plannedCost: summary.plannedCost + calculateStepPlannedCost(step), actualCost: summary.actualCost + step.actualCost, plannedDurationMinutes: summary.plannedDurationMinutes + step.plannedDurationMinutes, actualDurationMinutes: summary.actualDurationMinutes + step.actualDurationMinutes, resourceCount: summary.resourceCount + step.resources.length, wasteQuantity: summary.wasteQuantity + step.wasteQuantity }), { plannedCost: 0, actualCost: 0, plannedDurationMinutes: 0, actualDurationMinutes: 0, resourceCount: 0, wasteQuantity: 0 }) }
export function calculateWasteRate(input: number, output: number): number { return input <= 0 ? 0 : Math.max(0, Math.round(((input - output) / input) * 10000) / 100) }
export function minutesToLabel(minutes: number): string { const hours = Math.floor(minutes / 60); const rest = minutes % 60; return hours > 0 ? `${hours} h ${rest.toString().padStart(2, '0')} min` : `${rest} min` }
