import { zodResolver } from '@hookform/resolvers/zod'
import { useEffect } from 'react'
import { useForm, type Resolver } from 'react-hook-form'
import { Button } from '../../../../components/ui/Button'
import { Input } from '../../../../components/ui/Input'
import { Select } from '../../../../components/ui/Select'
import { Modal } from '../../../../components/ui/Modal'
import { stepResourceSchema, type StepResourceFormValues } from '../../schemas/stepResourceSchema'
import { RESOURCE_TYPES, type SapMaterialOption, type StepResourceInput } from '../../types/production.types'
import { ResourceSelector } from './ResourceSelector'
const defaults:StepResourceFormValues={sapCode:'',designation:'',resourceType:'RawMaterial',plannedQuantity:1,actualQuantity:0,unit:'kg',unitCost:0,availableStock:0,supplier:'',batchNumber:'',expirationDate:null}
export function StepResourceForm({open,initial,onClose,onSubmit}:{open:boolean;initial?:StepResourceInput;onClose:()=>void;onSubmit:(value:StepResourceInput)=>void}){const {register,handleSubmit,reset,setValue,watch,formState:{errors}}=useForm<StepResourceFormValues>({resolver:zodResolver(stepResourceSchema) as Resolver<StepResourceFormValues>,defaultValues:initial??defaults});useEffect(()=>reset(initial??defaults),[initial,reset]);const choose=(m:SapMaterialOption)=>{setValue('sapCode',m.sapCode);setValue('designation',m.designation);setValue('unit',m.unit);setValue('unitCost',m.unitCost);setValue('availableStock',m.availableStock);setValue('supplier',m.supplier);setValue('batchNumber',m.batchNumber);setValue('expirationDate',m.expirationDate)};const total=watch('plannedQuantity')*watch('unitCost');return <Modal open={open} onClose={onClose} title="Ressource de l’étape" className="max-w-3xl"><form onSubmit={handleSubmit(onSubmit)} className="space-y-4"><ResourceSelector onSelect={choose}/><div className="grid gap-3 md:grid-cols-2"><Input label="Code SAP" {...register('sapCode')} error={errors.sapCode?.message}/><Input label="Désignation" {...register('designation')} error={errors.designation?.message}/><Select label="Type" options={RESOURCE_TYPES.map((x)=>({label:x,value:x}))} {...register('resourceType')}/><Input label="Unité" {...register('unit')} error={errors.unit?.message}/><Input label="Quantité prévue" type="number" step="0.01" {...register('plannedQuantity')} error={errors.plannedQuantity?.message}/><Input label="Quantité réelle" type="number" step="0.01" {...register('actualQuantity')}/><Input label="Coût unitaire" type="number" step="0.01" {...register('unitCost')}/><Input label="Stock disponible" type="number" step="0.01" {...register('availableStock')}/><Input label="Fournisseur" {...register('supplier')}/><Input label="N° de lot" {...register('batchNumber')}/></div><p className="rounded-xl bg-blue-50 p-3 text-sm font-semibold text-blue-700">Coût calculé : {Number.isFinite(total)?total.toFixed(2):'0.00'} MAD</p><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={onClose}>Annuler</Button><Button type="submit">Ajouter la ressource</Button></div></form></Modal>}
