import { useEffect } from 'react'
import { useFieldArray, useFormContext, useWatch } from 'react-hook-form'
import { Plus, Trash2 } from 'lucide-react'
import { Input } from '../../../../components/ui/Input'
import { Select } from '../../../../components/ui/Select'
import { TextArea } from '../../../../components/ui/TextArea'
import { Button } from '../../../../components/ui/Button'
import { DEMAND_LEVELS, MARKET_TRENDS, RISK_TYPES, type DemandLevel, type MarketStudyInput, type MarketTrend } from '../../types/commercial.types'
import { calculateForecast, calculatePricing } from '../../utils/commercialCalculations'
import { formatCurrency } from '../../../production/utils/productionFormatters'
const demandLabels:Record<DemandLevel,string>={VeryLow:'Très faible',Low:'Faible',Medium:'Moyenne',High:'Élevée',VeryHigh:'Très élevée'}
const trendLabels:Record<MarketTrend,string>={Declining:'En baisse',Stable:'Stable',Growing:'En croissance',RapidlyGrowing:'Croissance rapide'}
export function GeneralInformationStep(){const{register}=useFormContext<MarketStudyInput>();return <Step title="Informations générales" description="Cadre, périmètre et responsable de l’étude"><Grid><Input label="Nom de l’étude" {...register('studyName')}/><Input label="Marché cible" {...register('targetMarket')}/><Input label="Zone géographique" {...register('geographicArea')}/><Input label="Segment client" {...register('customerSegment')}/><Input label="Date de l’étude" type="date" {...register('studyDate')}/><Input label="Responsable" {...register('managerName')}/></Grid></Step>}
export function MarketDataStep(){const{register}=useFormContext<MarketStudyInput>();return <Step title="Données du marché" description="Mesurez la taille, la dynamique et les canaux"><Grid><Input label="Taille estimée du marché" type="number" {...register('estimatedMarketSize')}/><Input label="Croissance annuelle %" type="number" step="0.1" {...register('annualGrowthRate')}/><Select label="Niveau de demande" options={DEMAND_LEVELS.map(x=>({label:demandLabels[x],value:x}))} {...register('demandLevel')}/><Select label="Tendance" options={MARKET_TRENDS.map(x=>({label:trendLabels[x],value:x}))} {...register('marketTrend')}/><Input label="Saisonnalité" {...register('seasonality')}/><Input label="Canaux de distribution" {...register('distributionChannels')}/><Input label="Zone de commercialisation" {...register('commercializationArea')}/></Grid></Step>}
export function TargetCustomersStep(){const{register}=useFormContext<MarketStudyInput>();return <Step title="Clients cibles" description="Décrivez les acheteurs et leurs comportements"><Grid><Input label="Type de client" {...register('customerType')}/><Input label="Tranche d’âge" {...register('ageRange')}/><Input label="Pouvoir d’achat" {...register('purchasingPower')}/><Input label="Fréquence d’achat" {...register('purchaseFrequency')}/><Input label="Sensibilité au prix (0–100)" type="number" {...register('priceSensitivity')}/></Grid><div className="mt-4 grid gap-4 md:grid-cols-2"><TextArea label="Habitudes de consommation" {...register('consumptionHabits')}/><TextArea label="Préférences" {...register('preferences')}/></div></Step>}
export function CompetitorsStep(){const{register,control}=useFormContext<MarketStudyInput>();const{fields,append,remove}=useFieldArray({control,name:'competitors'});return <Step title="Concurrents" description="Ajoutez les offres directement comparables"><div className="space-y-4">{fields.map((field,index)=><article key={field.id} className="rounded-xl border border-slate-200 p-4"><div className="mb-3 flex justify-between"><strong>Concurrent {index+1}</strong><Button type="button" variant="ghost" size="icon" onClick={()=>remove(index)} aria-label="Supprimer"><Trash2 className="size-4 text-red-500"/></Button></div><Grid><Input label="Entreprise" {...register(`competitors.${index}.competitorName`)}/><Input label="Produit" {...register(`competitors.${index}.productName`)}/><Input label="Prix" type="number" step="0.01" {...register(`competitors.${index}.price`)}/><Input label="Quantité" type="number" {...register(`competitors.${index}.quantity`)}/><Input label="Qualité estimée /100" type="number" {...register(`competitors.${index}.estimatedQuality`)}/><Input label="Part de marché %" type="number" {...register(`competitors.${index}.marketShare`)}/><Input label="Note client /5" type="number" step="0.1" {...register(`competitors.${index}.customerRating`)}/><Input label="Canaux" {...register(`competitors.${index}.salesChannels`)}/></Grid><div className="mt-3 grid gap-3 md:grid-cols-2"><TextArea label="Forces" {...register(`competitors.${index}.strengths`)}/><TextArea label="Faiblesses" {...register(`competitors.${index}.weaknesses`)}/></div></article>)}</div><Button type="button" variant="secondary" className="mt-4" onClick={()=>append({id:crypto.randomUUID(),competitorName:'',productName:'',price:0,quantity:1,estimatedQuality:50,marketShare:0,strengths:'',weaknesses:'',salesChannels:'',customerRating:3,imageUrl:null})}><Plus className="size-4"/>Ajouter un concurrent</Button></Step>}
export function PricingProfitabilityStep(){const{register,setValue,control}=useFormContext<MarketStudyInput>();const pricing=useWatch({control,name:'pricing'});
// oxlint-disable-next-line react-hooks/exhaustive-deps -- dépendances primitives pour éviter une boucle sur l'objet calculé.
useEffect(()=>{const result=calculatePricing(pricing);for(const[key,value]of Object.entries(result))setValue(`pricing.${key}` as keyof MarketStudyInput,value,{shouldValidate:false})},[pricing.productionCost,pricing.proposedSalePrice,pricing.estimatedMarketingCost,pricing.estimatedDistributionCost,pricing.estimatedCommission,setValue]);return <Step title="Prix et rentabilité" description="Les marges et le seuil sont recalculés automatiquement"><Grid><Input label="Coût de production" type="number" step="0.01" {...register('pricing.productionCost')}/><Input label="Prix proposé" type="number" step="0.01" {...register('pricing.proposedSalePrice')}/><Input label="Prix moyen marché" type="number" step="0.01" {...register('pricing.averageMarketPrice')}/><Input label="Prix minimum" type="number" {...register('pricing.minimumAcceptablePrice')}/><Input label="Prix maximum" type="number" {...register('pricing.maximumAcceptablePrice')}/><Input label="Marge souhaitée %" type="number" {...register('pricing.desiredMargin')}/><Input label="Marketing unitaire" type="number" step="0.01" {...register('pricing.estimatedMarketingCost')}/><Input label="Distribution unitaire" type="number" step="0.01" {...register('pricing.estimatedDistributionCost')}/><Input label="Commission unitaire" type="number" step="0.01" {...register('pricing.estimatedCommission')}/></Grid><div className="mt-4 grid gap-3 sm:grid-cols-3"><Result label="Marge unitaire" value={formatCurrency(pricing.calculatedMargin)}/><Result label="Taux de marge" value={`${pricing.marginRate.toFixed(1)}%`}/><Result label="Seuil de rentabilité" value={`${pricing.breakEvenUnits} unités`}/></div></Step>}
export function SalesForecastStep(){const{register,setValue,control}=useFormContext<MarketStudyInput>();const price=useWatch({control,name:'pricing.proposedSalePrice'}),monthly=useWatch({control,name:'forecast.monthlySalesVolume'}),annual=useWatch({control,name:'forecast.annualSalesVolume'});useEffect(()=>{const v=calculateForecast(price,monthly,annual);setValue('forecast.monthlyRevenue',v.monthlyRevenue);setValue('forecast.annualRevenue',v.annualRevenue)},[price,monthly,annual,setValue]);return <Step title="Prévisions commerciales" description="Projetez volumes, revenus et croissance"><Grid><Input label="Volume mensuel" type="number" {...register('forecast.monthlySalesVolume')}/><Input label="Volume annuel" type="number" {...register('forecast.annualSalesVolume')}/><Input label="Seuil atteint en (mois)" type="number" {...register('forecast.breakEvenPeriodMonths')}/><Input label="Croissance attendue %" type="number" {...register('forecast.expectedGrowthRate')}/></Grid><div className="mt-4 grid gap-3 sm:grid-cols-2"><Result label="Chiffre d’affaires mensuel" value={formatCurrency(monthly*price)}/><Result label="Chiffre d’affaires annuel" value={formatCurrency(annual*price)}/></div></Step>}
export function RisksStep(){const{register,control}=useFormContext<MarketStudyInput>();const{fields,append,remove}=useFieldArray({control,name:'risks'});return <Step title="Risques" description="Évaluez probabilité × impact sur une échelle de 1 à 5"><div className="space-y-3">{fields.map((field,index)=><article key={field.id} className="grid gap-3 rounded-xl border border-slate-200 p-4 md:grid-cols-5"><Select label="Type" options={RISK_TYPES.map(x=>({label:x,value:x}))} {...register(`risks.${index}.riskType`)}/><Input label="Probabilité" type="number" min="1" max="5" {...register(`risks.${index}.probability`)}/><Input label="Impact" type="number" min="1" max="5" {...register(`risks.${index}.impact`)}/><Input label="Description" {...register(`risks.${index}.description`)}/><div className="flex items-end gap-1"><Input label="Mitigation" {...register(`risks.${index}.mitigationAction`)}/><Button type="button" size="icon" variant="ghost" onClick={()=>remove(index)}><Trash2 className="size-4 text-red-500"/></Button></div></article>)}</div><Button type="button" variant="secondary" className="mt-4" onClick={()=>append({id:crypto.randomUUID(),riskType:'Competitive',probability:3,impact:3,description:'',mitigationAction:''})}><Plus className="size-4"/>Ajouter un risque</Button></Step>}
export function CommercialScoresStep(){const{register}=useFormContext<MarketStudyInput>();const fields=[['demandPotentialScore','Potentiel de demande'],['pricePositioningScore','Positionnement prix'],['competitiveAdvantageScore','Avantage concurrentiel'],['distributionScore','Distribution'],['productAttractivenessScore','Attractivité produit'],['profitabilityScore','Rentabilité'],['commercialRiskScore','Maîtrise du risque'],['marketFitScore','Adéquation marché']] as const;return <Step title="Notes commerciales" description="Attribuez une note de 0 à 100 pour chaque critère"><div className="grid gap-4 md:grid-cols-2">{fields.map(([name,label])=><Input key={name} label={label} type="range" min="0" max="100" {...register(`scores.${name}`)}/>)}</div></Step>}
export function MarketStudyReviewStep(){const data=useWatch<MarketStudyInput>();return <Step title="Résumé avant validation" description="Vérifiez les données principales avant le calcul final"><dl className="grid gap-4 md:grid-cols-2"><Review label="Étude" value={data.studyName}/><Review label="Marché" value={data.targetMarket}/><Review label="Demande" value={String(data.demandLevel)}/><Review label="Tendance" value={String(data.marketTrend)}/><Review label="Prix proposé" value={formatCurrency(data.pricing?.proposedSalePrice??0)}/><Review label="CA annuel" value={formatCurrency(data.forecast?.annualRevenue??0)}/><Review label="Concurrents" value={String(data.competitors?.length??0)}/><Review label="Risques" value={String(data.risks?.length??0)}/></dl></Step>}
function Step({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="surface-card p-5 sm:p-6"><h2 className="text-lg font-bold text-slate-950">{title}</h2><p className="mb-5 mt-1 text-sm text-slate-500">{description}</p>{children}</section>}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-4 md:grid-cols-2">{children}</div>}
function Result({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-blue-50 p-4"><p className="text-xs text-blue-500">{label}</p><p className="mt-1 font-bold text-blue-900">{value}</p></div>}
function Review({label,value}:{label:string;value:string|undefined}){return <div className="border-b border-slate-100 pb-3"><dt className="text-xs uppercase text-slate-400">{label}</dt><dd className="mt-1 font-semibold text-slate-800">{value||'—'}</dd></div>}
