import { Archive, MessageSquarePlus, MoreHorizontal, Search, Sparkles, Trash2 } from 'lucide-react'
import { format, isAfter, isToday, subDays } from 'date-fns'
import { fr } from 'date-fns/locale'
import type { AiConversationSummary } from '../types/ai.types'

export function ConversationSidebar({ conversations, activeId, search, onSearch, onNew, onOpen, onRename, onArchive, onDelete }: { conversations: AiConversationSummary[]; activeId?: string; search: string; onSearch: (value: string) => void; onNew: () => void; onOpen: (id: string) => void; onRename: (item: AiConversationSummary) => void; onArchive: (item: AiConversationSummary) => void; onDelete: (item: AiConversationSummary) => void }) {
  const sections = [['Aujourd’hui', conversations.filter(item => isToday(new Date(item.lastMessageAt)))], ['7 derniers jours', conversations.filter(item => !isToday(new Date(item.lastMessageAt)) && isAfter(new Date(item.lastMessageAt), subDays(new Date(), 7)))], ['Plus ancien', conversations.filter(item => !isAfter(new Date(item.lastMessageAt), subDays(new Date(), 7)))]] as const
  return <aside className="flex h-full min-h-0 flex-col bg-slate-950 text-slate-300"><div className="border-b border-white/10 p-4"><div className="mb-4 flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-gradient-to-br from-violet-500 to-blue-500 text-white shadow-lg shadow-violet-950/40"><Sparkles className="size-4" /></span><div><p className="font-bold text-white">SMART PRODUCT</p><p className="text-[10px] tracking-[.16em] text-violet-300 uppercase">ProductApp intelligence</p></div></div><button type="button" onClick={onNew} className="flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-white text-sm font-bold text-slate-950 transition hover:bg-violet-50"><MessageSquarePlus className="size-4" />Nouveau chat</button><label className="mt-3 flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3"><Search className="size-4 text-slate-500" /><input value={search} onChange={event => onSearch(event.target.value)} placeholder="Rechercher…" className="h-10 min-w-0 flex-1 bg-transparent text-sm text-white outline-none placeholder:text-slate-500" /></label></div><div className="min-h-0 flex-1 overflow-y-auto px-2 py-4">{sections.map(([label, items]) => items.length > 0 && <section key={label} className="mb-5"><h2 className="mb-1 px-3 text-[10px] font-bold tracking-[.14em] text-slate-500 uppercase">{label}</h2><div className="space-y-1">{items.map(item => <div key={item.id} className={`group flex items-center rounded-xl transition ${activeId === item.id ? 'bg-white/12 text-white' : 'hover:bg-white/6'}`}><button type="button" onClick={() => onOpen(item.id)} className="min-w-0 flex-1 px-3 py-2.5 text-left"><span className="block truncate text-sm font-medium">{item.title}</span><span className="mt-0.5 block truncate text-[10px] text-slate-500">{item.isArchived ? 'Archivée · ' : ''}{format(new Date(item.lastMessageAt), 'd MMM · HH:mm', { locale: fr })}</span></button><div className="mr-1 flex opacity-0 transition group-hover:opacity-100 group-focus-within:opacity-100"><button title="Renommer" onClick={() => onRename(item)} className="grid size-7 place-items-center rounded-md hover:bg-white/10"><MoreHorizontal className="size-3.5" /></button><button title={item.isArchived ? 'Restaurer' : 'Archiver'} onClick={() => onArchive(item)} className="grid size-7 place-items-center rounded-md hover:bg-white/10"><Archive className="size-3.5" /></button><button title="Supprimer" onClick={() => onDelete(item)} className="grid size-7 place-items-center rounded-md hover:bg-red-500/20 hover:text-red-300"><Trash2 className="size-3.5" /></button></div></div>)}</div></section>)}</div></aside>
}
