import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, PolarAngleAxis, PolarGrid, Radar, RadarChart, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from 'recharts'
import type { CommercialRisk, CommercialScores, FeasibilityResult, MarketTrendPoint } from '../../types/commercial.types'
import { ChartCard } from '../../../../components/charts/ChartCard'
const colors=['#10b981','#f59e0b','#ef4444','#2563eb','#8b5cf6']
export function FeasibilityGauge({result}:{result:FeasibilityResult}){const data=[{name:'Score',value:result.globalScore},{name:'Reste',value:100-result.globalScore}];return <div className="relative h-56"><ResponsiveContainer><PieChart><Pie data={data} dataKey="value" startAngle={180} endAngle={0} innerRadius={70} outerRadius={95} cx="50%" cy="75%"><Cell fill={result.globalScore>=70?'#10b981':result.globalScore>=48?'#f59e0b':'#ef4444'}/><Cell fill="#e2e8f0"/></Pie></PieChart></ResponsiveContainer><div className="absolute inset-x-0 bottom-5 text-center"><strong className="text-4xl text-slate-950">{result.globalScore}</strong><span className="text-slate-400">/100</span></div></div>}
export function CommercialCriteriaRadar({scores}:{scores:CommercialScores}){const labels:Record<keyof CommercialScores,string>={demandPotentialScore:'Demande',pricePositioningScore:'Prix',competitiveAdvantageScore:'Avantage',distributionScore:'Distribution',productAttractivenessScore:'Attractivité',profitabilityScore:'Rentabilité',commercialRiskScore:'Risques',marketFitScore:'Market fit'};const data=Object.entries(scores).map(([key,value])=>({criterion:labels[key as keyof CommercialScores],score:value}));return <ResponsiveContainer><RadarChart data={data}><PolarGrid/><PolarAngleAxis dataKey="criterion" tick={{fontSize:10}}/><Radar dataKey="score" stroke="#2563eb" fill="#2563eb" fillOpacity={.25}/><Tooltip/></RadarChart></ResponsiveContainer>}
export function RiskImpactMatrix({risks}:{risks:CommercialRisk[]}){const data=risks.map(r=>({x:r.probability,y:r.impact,z:r.probability*r.impact,name:r.description}));return <ResponsiveContainer><ScatterChart margin={{top:15,right:20,bottom:10,left:0}}><CartesianGrid/><XAxis type="number" dataKey="x" name="Probabilité" domain={[0,5]}/><YAxis type="number" dataKey="y" name="Impact" domain={[0,5]}/><ZAxis dataKey="z" range={[80,500]}/><Tooltip cursor={{strokeDasharray:'3 3'}}/><Scatter data={data} fill="#ef4444"/></ScatterChart></ResponsiveContainer>}
export function CostPriceChart({production,proposed,market}:{production:number;proposed:number;market:number}){return <ResponsiveContainer><BarChart data={[{name:'Prix',production,proposed,market}]}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Legend/><Bar dataKey="production" name="Coût de revient" fill="#64748b"/><Bar dataKey="proposed" name="Prix proposé" fill="#2563eb"/><Bar dataKey="market" name="Prix marché" fill="#10b981"/></BarChart></ResponsiveContainer>}
export function TrendCharts({trends}:{trends:MarketTrendPoint[]}){return <><ChartCard title="Évolution mensuelle de la demande"><ResponsiveContainer><LineChart data={trends}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip/><Line dataKey="demand" stroke="#2563eb" strokeWidth={3}/></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Ventes et chiffre d’affaires prévisionnels"><ResponsiveContainer><LineChart data={trends}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip/><Legend/><Line dataKey="forecastSales" name="Ventes" stroke="#8b5cf6" strokeWidth={2}/><Line dataKey="revenue" name="CA" stroke="#10b981" strokeWidth={2}/></LineChart></ResponsiveContainer></ChartCard></>}
export function RecommendationPie({values}:{values:{name:string;value:number}[]}){return <ResponsiveContainer><PieChart><Pie data={values} dataKey="value" nameKey="name" innerRadius={55} outerRadius={90}>{values.map((v,i)=><Cell key={v.name} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer>}
