import { actionsByModule, platformActivity, productsEvolution } from '../mocks/adminDashboard.mock'
import { sharedMockRepository } from '../../../mocks/shared/sharedMock.repository'
import type { UserRole } from '../../../types/auth'
import type { AdminDashboardData, AdminUser, UserFormInput, UserStatus } from '../types/admin.types'
const wait=async(ms=120)=>new Promise<void>(resolve=>window.setTimeout(resolve,ms))
const find=(id:string):AdminUser=>{const user=sharedMockRepository.read().users.find(item=>item.id===id);if(!user)throw new Error('Utilisateur introuvable.');return user}
export const adminMockService={
async getUsers(){await wait();return sharedMockRepository.read().users},async getUser(id:string){await wait();return find(id)},
async createUser(input:UserFormInput){await wait();if(sharedMockRepository.read().users.some(u=>u.email.toLowerCase()===input.email.toLowerCase()))throw new Error('Cette adresse e-mail est déjà utilisée.');const now=new Date().toISOString(),user:AdminUser={id:`usr-${crypto.randomUUID()}`,...input,fullName:`${input.firstName} ${input.lastName}`,createdAt:now,updatedAt:now,lastLoginAt:null,avatarUrl:null};sharedMockRepository.transaction({audit:{action:'USER_CREATED',module:'Users',description:`Création du compte ${user.fullName}.`,entityType:'ApplicationUser',entityId:user.id},notifications:[{recipientRole:'Administrator',title:'Utilisateur créé',message:`Le compte ${user.fullName} a été créé.`,type:'success',relatedEntityType:'ApplicationUser',relatedEntityId:user.id}]},db=>{db.users=[user,...db.users]});return user},
async updateUser(id:string,input:UserFormInput){await wait();const current=find(id),updated={...current,...input,fullName:`${input.firstName} ${input.lastName}`,updatedAt:new Date().toISOString()};sharedMockRepository.transaction({audit:{action:'USER_UPDATED',module:'Users',description:`Mise à jour du compte ${updated.fullName}.`,entityType:'ApplicationUser',entityId:id}},db=>{db.users=db.users.map(u=>u.id===id?updated:u)});return updated},
async deleteUser(id:string){await wait();const user=find(id);sharedMockRepository.transaction({audit:{action:'USER_DELETED',module:'Users',description:`Suppression du compte ${user.fullName}.`,level:'Warning',entityType:'ApplicationUser',entityId:id}},db=>{db.users=db.users.filter(u=>u.id!==id)})},
async setUserStatus(id:string,status:UserStatus){await wait();const current=find(id),updated={...current,status,updatedAt:new Date().toISOString()};sharedMockRepository.transaction({audit:{action:'USER_STATUS_CHANGED',module:'Users',description:`Statut de ${updated.fullName} modifié en ${status}.`,level:status==='Active'?'Information':'Warning',entityType:'ApplicationUser',entityId:id}},db=>{db.users=db.users.map(u=>u.id===id?updated:u)});return updated},
async changeUserRole(id:string,role:UserRole){await wait();const current=find(id),updated={...current,role,updatedAt:new Date().toISOString()};sharedMockRepository.transaction({audit:{action:'USER_ROLE_CHANGED',module:'Users',description:`Rôle de ${updated.fullName} modifié en ${role}.`,entityType:'ApplicationUser',entityId:id},notifications:[{recipientRole:'Administrator',title:'Rôle modifié',message:`${updated.fullName} possède maintenant le rôle ${role}.`,type:'information',relatedEntityType:'ApplicationUser',relatedEntityId:id}]},db=>{db.users=db.users.map(u=>u.id===id?updated:u)});return updated},
async simulatePasswordReset(id:string){await wait();const user=find(id);sharedMockRepository.transaction({audit:{action:'PASSWORD_RESET_SIMULATED',module:'Users',description:`Réinitialisation simulée pour ${user.fullName}.`,entityType:'ApplicationUser',entityId:id}},()=>undefined)},
async getLogs(){await wait();return sharedMockRepository.read().auditLogs},
async getDashboard():Promise<AdminDashboardData>{await wait();const db=sharedMockRepository.read(),users=db.users,logs=db.auditLogs;const usersByRole=(['Administrator','ProductionManager','CommercialManager'] as const).map(role=>({role,count:users.filter(u=>u.role===role).length}));const recommendations=['Viable','ToOptimize','NotViable'].map(type=>({type,count:db.marketStudies.filter(s=>s.feasibility?.recommendation===type).length}));const statusMap=db.products.reduce<Record<string,number>>((a,p)=>({...a,[p.status]:(a[p.status]??0)+1}),{});return{metrics:[{id:'users-total',label:'Utilisateurs',value:users.length,detail:'Comptes enregistrés',tone:'blue'},{id:'users-active',label:'Utilisateurs actifs',value:users.filter(u=>u.status==='Active').length,detail:'Comptes opérationnels',tone:'emerald'},{id:'users-inactive',label:'Comptes désactivés',value:users.filter(u=>u.status!=='Active').length,detail:'Inactifs ou suspendus',tone:'amber'},{id:'production-managers',label:'Responsables Production',value:usersByRole.find(x=>x.role==='ProductionManager')?.count??0,detail:'Accès Production',tone:'blue'},{id:'commercial-managers',label:'Responsables Commercial',value:usersByRole.find(x=>x.role==='CommercialManager')?.count??0,detail:'Accès Commercial',tone:'violet'},{id:'administrators',label:'Administrateurs',value:usersByRole.find(x=>x.role==='Administrator')?.count??0,detail:'Accès complet',tone:'violet'},{id:'products',label:'Produits',value:db.products.length,detail:`${db.productVersions.length} versions`,tone:'blue'},{id:'experiments',label:'Expériences',value:db.experiments.length,detail:`${db.experiments.filter(e=>e.endDate).length} terminées`,tone:'emerald'},{id:'studies',label:'Études commerciales',value:db.marketStudies.length,detail:`${db.marketStudies.filter(s=>s.status==='InProgress').length} en cours`,tone:'violet'},{id:'viable',label:'Produits viables',value:recommendations[0]?.count??0,detail:'Décisions favorables',tone:'emerald'},{id:'optimize',label:'À optimiser',value:recommendations[1]?.count??0,detail:'Demandes actives',tone:'amber'},{id:'non-viable',label:'Produits non viables',value:recommendations[2]?.count??0,detail:'Décisions défavorables',tone:'amber'},{id:'errors',label:'Erreurs récentes',value:logs.filter(l=>l.level==='Error'||l.level==='Critical').length,detail:'Événements à surveiller',tone:'amber'}],usersByRole,productsEvolution,productsByStatus:Object.entries(statusMap).map(([status,count])=>({status,count})),recommendations,platformActivity,actionsByModule,recentLogs:logs.slice(0,8)}}}
