import { CalendarDays, Clock3, Mail, Phone } from 'lucide-react'
import type { AdminUser } from '../../types/admin.types'
import { formatAdminDateTime, getInitials } from '../../utils/adminFormatters'
import { UserRoleBadge } from './UserRoleBadge'
import { UserStatusBadge } from './UserStatusBadge'

export function UserProfileCard({ user }: { user: AdminUser }) {
  const details = [{ icon: Mail, label: 'E-mail', value: user.email }, { icon: Phone, label: 'Téléphone', value: user.phoneNumber }, { icon: CalendarDays, label: 'Compte créé', value: formatAdminDateTime(user.createdAt) }, { icon: Clock3, label: 'Dernière connexion', value: user.lastLoginAt ? formatAdminDateTime(user.lastLoginAt) : 'Jamais' }]
  return <div className="surface-card overflow-hidden"><div className="h-28 bg-gradient-to-r from-slate-950 via-blue-950 to-blue-700" /><div className="px-5 pb-6 sm:px-7"><div className="-mt-10 flex flex-col gap-4 sm:flex-row sm:items-end"><span className="grid size-20 place-items-center rounded-2xl border-4 border-white bg-blue-600 text-xl font-bold text-white shadow-lg">{getInitials(user.firstName, user.lastName)}</span><div className="min-w-0 flex-1 pb-1"><h2 className="text-xl font-bold text-slate-950">{user.fullName}</h2><div className="mt-2 flex flex-wrap gap-2"><UserRoleBadge role={user.role} /><UserStatusBadge status={user.status} /></div></div></div><div className="mt-7 grid gap-4 sm:grid-cols-2">{details.map(({ icon: Icon, label, value }) => <div key={label} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center gap-2 text-xs font-semibold tracking-wide text-slate-400 uppercase"><Icon className="size-4" />{label}</div><p className="mt-2 break-words text-sm font-medium text-slate-800">{value}</p></div>)}</div><div className="mt-4 grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-500 uppercase">Identifiant</p><p className="mt-2 font-mono text-xs text-slate-700">{user.id}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-500 uppercase">Dernière mise à jour</p><p className="mt-2 text-sm text-slate-700">{formatAdminDateTime(user.updatedAt)}</p></div></div></div></div>
}
