const memory=new Map<string,string>()
Object.assign(globalThis,{window:{setTimeout,localStorage:{getItem:(key:string)=>memory.get(key)??null,setItem:(key:string,value:string)=>memory.set(key,value),removeItem:(key:string)=>memory.delete(key)}}})
const {sharedMockRepository}=await import('../src/mocks/shared/sharedMock.repository')
const {validateSharedMockDatabase}=await import('../src/mocks/shared/sharedMock.validation')
const {productionMockService}=await import('../src/features/production/services/productionMockService')
const {commercialMockService}=await import('../src/features/commercial/services/commercialMockService')
const {adminMockService}=await import('../src/features/admin/services/adminMockService')
const {defaultStudyInput}=await import('../src/features/commercial/mocks/marketStudies.mock')
sharedMockRepository.reset()
sharedMockRepository.setActor({id:'usr-002',name:'Salma Benali',role:'ProductionManager',ipAddress:'10.20.2.31'})
const product=await productionMockService.createProduct({name:'Biscuit Workflow Test',internalReference:'WF-BIS-001',sapCode:'SAP-WF-001',category:'Biscuit test',description:'Produit temporaire de vérification du workflow partagé.',imageUrl:null,targetSalePrice:21,batchQuantity:500,productionUnit:'kg',status:'Draft'})
const now=new Date().toISOString(),stepId=`step-${crypto.randomUUID()}`
await productionMockService.saveProcess({id:`process-${product.id}`,productId:product.id,productVersion:1,version:1,updatedAt:now,savedAt:now,steps:[{id:stepId,productId:product.id,name:'Cuisson test',description:'Étape complète de validation.',order:1,plannedDurationMinutes:25,actualDurationMinutes:27,plannedCost:450,actualCost:470,temperature:180,pressure:null,humidity:20,plannedOutputQuantity:500,actualOutputQuantity:485,wasteQuantity:15,equipment:['Four test'],operatorCount:2,laborCost:120,energyConsumption:55,instructions:'Cuire le lot test.',validationCriteria:'Température et couleur conformes.',observations:'Conforme.',status:'Validated',resources:[{id:`res-${crypto.randomUUID()}`,stepId,sapCode:'SAP-FARINE',designation:'Farine test',resourceType:'RawMaterial',plannedQuantity:300,actualQuantity:295,unit:'kg',unitCost:4,totalCost:1200,availableStock:900, supplier:'SAP mock',batchNumber:'LOT-WF',expirationDate:'2027-01-01',availabilityStatus:'Available'}]}]})
await productionMockService.createExperiment({name:'Expérience workflow',productId:product.id,productVersion:1,startDate:now,endDate:now,objective:'Valider le workflow complet.',hypothesis:'Le processus est stable et rentable.',plannedQuantity:500,actualQuantity:485,plannedCost:1770,actualCost:1810,plannedDuration:25,actualDuration:27,wasteRate:3,result:'Success',observations:'Essai conforme.',conclusion:'Prêt pour étude.'})
await productionMockService.sendToCommercial(product.id)
sharedMockRepository.setActor({id:'usr-003',name:'Youssef Alaoui',role:'CommercialManager',ipAddress:'10.20.3.11'})
const commercialProduct=await commercialMockService.getProduct(product.id)
const studyInput=defaultStudyInput(product.id,1,commercialProduct.productionCost,product.targetSalePrice)
studyInput.studyName='Étude workflow intégrée'
const study=await commercialMockService.saveStudy(studyInput,'Validated')
await commercialMockService.createOptimizationRequest({productId:product.id,productVersion:1,message:'Réduire les pertes du lot test.',priority:'High',requestedChanges:['Réduire les pertes'],commercialManagerName:'Youssef Alaoui'})
sharedMockRepository.setActor({id:'usr-002',name:'Salma Benali',role:'ProductionManager',ipAddress:'10.20.2.31'})
const requests=await productionMockService.getOptimizationRequests()
const version=await productionMockService.createVersion(product.id)
sharedMockRepository.setActor({id:'usr-001',name:'Amine El Mansouri',role:'Administrator',ipAddress:'10.20.1.14'})
const logs=await adminMockService.getLogs(),db=sharedMockRepository.read(),issues=validateSharedMockDatabase(db)
const checks={productVisibleCommercial:commercialProduct.product.id===product.id,studyCalculated:Boolean(study.feasibility),optimizationVisibleProduction:requests.some(item=>item.productId===product.id),newVersionSameProduct:version.id===product.id&&version.version===2,auditActions:['PRODUCT_CREATED','EXPERIMENT_COMPLETED','PRODUCT_SENT_TO_MARKET','MARKET_STUDY_CREATED','FEASIBILITY_CALCULATED','OPTIMIZATION_REQUESTED','PRODUCT_VERSION_CREATED'].every(action=>logs.some(log=>log.action===action)),notificationsCreated:db.notifications.some(item=>item.relatedEntityId===product.id),relationIssues:issues}
if(Object.entries(checks).some(([key,value])=>key!=='relationIssues'&&value!==true)||issues.length)throw new Error(`Workflow invalide: ${JSON.stringify(checks)}`)
console.log(JSON.stringify(checks,null,2))
