import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, PolarAngleAxis, PolarGrid, Radar, RadarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ChartCard } from '../../../../components/charts/ChartCard'
import type { AdminDashboardData } from '../../types/admin.types'

const roleLabels: Record<string, string> = { Administrator: 'Administrateurs', ProductionManager: 'Production', CommercialManager: 'Commercial' }
const palette = ['#2563eb', '#8b5cf6', '#10b981', '#f59e0b']
const tooltipStyle = { borderRadius: 12, borderColor: '#e2e8f0', boxShadow: '0 10px 25px rgba(15,23,42,.08)' }

export function AdminDashboardCharts({ data }: { data: AdminDashboardData }) {
  const roleData = data.usersByRole.map((item) => ({ ...item, label: roleLabels[item.role] ?? item.role }))
  return <section aria-label="Analyses de la plateforme" className="grid min-w-0 gap-6 xl:grid-cols-2">
    <ChartCard title="Utilisateurs par rôle" description="Répartition des comptes enregistrés"><ResponsiveContainer width="100%" height="100%"><BarChart data={roleData}><CartesianGrid strokeDasharray="4 4" stroke="#e2e8f0" vertical={false} /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: '#64748b', fontSize: 11 }} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{ fill: '#64748b', fontSize: 11 }} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="count" name="Utilisateurs" fill="#2563eb" radius={[8, 8, 0, 0]} /></BarChart></ResponsiveContainer></ChartCard>
    <ChartCard title="Évolution du nombre de produits" description="Progression du référentiel sur six mois"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.productsEvolution}><CartesianGrid strokeDasharray="4 4" stroke="#e2e8f0" vertical={false} /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: '#64748b', fontSize: 12 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#64748b', fontSize: 11 }} /><Tooltip contentStyle={tooltipStyle} /><Line type="monotone" dataKey="products" name="Produits" stroke="#8b5cf6" strokeWidth={3} dot={{ r: 4, fill: '#8b5cf6' }} /></LineChart></ResponsiveContainer></ChartCard>
    <ChartCard title="Produits par statut" description="Synthèse de la viabilité du portefeuille"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.productsByStatus} dataKey="count" nameKey="status" innerRadius={65} outerRadius={95} paddingAngle={4}>{data.productsByStatus.map((item, index) => <Cell key={item.status} fill={palette[index % palette.length]} />)}</Pie><Tooltip contentStyle={tooltipStyle} /><Legend /></PieChart></ResponsiveContainer></ChartCard>
    <ChartCard title="Recommandations commerciales" description="Décisions proposées sur les études finalisées"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.recommendations} layout="vertical" margin={{ left: 12 }}><CartesianGrid strokeDasharray="4 4" stroke="#e2e8f0" horizontal={false} /><XAxis type="number" axisLine={false} tickLine={false} /><YAxis type="category" dataKey="type" width={82} axisLine={false} tickLine={false} tick={{ fill: '#64748b', fontSize: 11 }} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="count" name="Recommandations" fill="#10b981" radius={[0, 8, 8, 0]} /></BarChart></ResponsiveContainer></ChartCard>
    <ChartCard title="Activité de la plateforme" description="Actions et erreurs enregistrées par jour"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.platformActivity}><defs><linearGradient id="activityGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#2563eb" stopOpacity={0.35} /><stop offset="95%" stopColor="#2563eb" stopOpacity={0.03} /></linearGradient></defs><CartesianGrid strokeDasharray="4 4" stroke="#e2e8f0" vertical={false} /><XAxis dataKey="day" axisLine={false} tickLine={false} /><YAxis axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltipStyle} /><Legend /><Area type="monotone" dataKey="actions" name="Actions" stroke="#2563eb" fill="url(#activityGradient)" strokeWidth={2} /><Line type="monotone" dataKey="errors" name="Erreurs" stroke="#ef4444" strokeWidth={2} /></AreaChart></ResponsiveContainer></ChartCard>
    <ChartCard title="Actions effectuées par module" description="Volume d’activité fonctionnelle"><ResponsiveContainer width="100%" height="100%"><RadarChart data={data.actionsByModule}><PolarGrid stroke="#e2e8f0" /><PolarAngleAxis dataKey="module" tick={{ fill: '#64748b', fontSize: 10 }} /><Radar name="Actions" dataKey="actions" stroke="#8b5cf6" fill="#8b5cf6" fillOpacity={0.22} strokeWidth={2} /><Tooltip contentStyle={tooltipStyle} /></RadarChart></ResponsiveContainer></ChartCard>
  </section>
}
