import { Boxes, ChevronsUpDown, Sparkles } from 'lucide-react'
import { NavLink } from 'react-router-dom'
import { navigationGroups } from '../../routes/navigation'
import type { UserRole } from '../../types/auth'
import type { NavigationGroup } from '../../types/navigation'
import { cn } from '../../utils/cn'
import { RoleBadge } from './RoleBadge'

interface SidebarProps { role: UserRole; onNavigate?: () => void; compact?: boolean }
const smartProductGroup: NavigationGroup = { label: 'Intelligence', items: [{ label: 'SMART PRODUCT', path: '/ai', icon: Sparkles, roles: ['Administrator', 'ProductionManager', 'CommercialManager'], badge: 'IA' }] }
export function Sidebar({ role, onNavigate, compact = false }: SidebarProps) {
  const groups = [smartProductGroup, ...navigationGroups].map((group) => ({ ...group, items: group.items.filter((item) => item.roles.includes(role)) })).filter((group) => group.items.length > 0)
  return <div className="flex h-full flex-col bg-slate-950 text-slate-300"><div className="flex h-[4.5rem] items-center gap-3 border-b border-white/10 px-5"><span className="grid size-10 place-items-center rounded-xl bg-blue-600 text-white shadow-lg shadow-blue-950/40"><Boxes className="size-5" /></span>{!compact && <div><p className="font-bold tracking-tight text-white">ProductApp</p><p className="text-[11px] text-slate-400">Operations Intelligence</p></div>}</div><div className="border-b border-white/10 p-4"><button type="button" className="flex w-full items-center gap-3 rounded-xl bg-white/5 p-2 text-left hover:bg-white/10"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-gradient-to-br from-blue-500 to-violet-600 text-xs font-bold text-white">PA</span>{!compact && <span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-white">ProductApp Industrie</span><RoleBadge role={role} compact /></span>}<ChevronsUpDown className="size-4 text-slate-500" /></button></div><nav className="flex-1 space-y-6 overflow-y-auto px-3 py-5" aria-label="Navigation principale">{groups.map((group) => <section key={group.label}><h2 className={cn('mb-2 px-3 text-[10px] font-semibold tracking-[.18em] text-slate-500 uppercase', compact && 'sr-only')}>{group.label}</h2><ul className="space-y-1">{group.items.map((item) => { const Icon = item.icon; return <li key={item.label}>{item.disabled ? <div className="flex cursor-not-allowed items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-slate-600" title="Fonctionnalité prévue dans une prochaine étape"><Icon className="size-[18px] shrink-0" /><span className={cn('flex-1', compact && 'sr-only')}>{item.label}</span>{item.badge && !compact && <span className="text-[9px] font-semibold uppercase">{item.badge}</span>}</div> : <NavLink to={item.path ?? '/'} onClick={onNavigate} className={({ isActive }) => cn('flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition', isActive ? 'bg-blue-600 text-white shadow-lg shadow-blue-950/30' : 'text-slate-400 hover:bg-white/5 hover:text-white')}><Icon className="size-[18px] shrink-0" /><span className={cn('flex-1', compact && 'sr-only')}>{item.label}</span></NavLink>}</li> })}</ul></section>)}</nav><div className="border-t border-white/10 p-4"><div className="rounded-xl bg-white/5 p-3"><p className="text-xs font-semibold text-slate-200">Environnement démo</p><p className="mt-1 text-[11px] leading-4 text-slate-500">Données locales · API non connectée</p></div></div></div>
}
