import { ArrowRight, Beaker, Clock3, Coins, Layers3 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Button } from '../../../../components/ui/Button'
import { ProductStatusBadge } from '../../../production/components/products/ProductStatusBadge'
import { formatCurrency } from '../../../production/utils/productionFormatters'
import { minutesToLabel } from '../../../production/utils/productionCalculations'
import type { CommercialProductView } from '../../types/commercial.types'
export function CommercialProductCard({view,onStudy}:{view:CommercialProductView;onStudy:()=>void}){const p=view.product;return <article className="surface-card overflow-hidden"><div className="h-28 bg-gradient-to-br from-blue-600 via-cyan-600 to-slate-800 p-5 text-white"><p className="text-xs font-semibold uppercase tracking-widest opacity-75">{p.category}</p><h2 className="mt-2 text-lg font-bold">{p.name}</h2></div><div className="p-5"><div className="flex justify-between gap-3"><p className="text-xs text-slate-400">Version {p.version} · lot {p.batchQuantity} {p.productionUnit}</p><ProductStatusBadge status={p.status}/></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><Metric icon={Coins} label="Coût" value={formatCurrency(view.productionCost)}/><Metric icon={Clock3} label="Durée" value={minutesToLabel(view.totalDurationMinutes)}/><Metric icon={Layers3} label="Étapes" value={String(view.stepCount)}/><Metric icon={Beaker} label="Essais" value={String(view.experiments.length)}/></div><p className="mt-4 text-sm text-slate-500">Dernier résultat : <strong className="text-slate-700">{view.latestExperimentResult??'Non disponible'}</strong> · pertes {view.wasteRate}%</p><div className="mt-4 flex gap-2"><Link className="flex-1" to={`/commercial/products/${p.id}`}><Button className="w-full" variant="secondary">Fiche technique</Button></Link><Button onClick={onStudy}>{view.study?'Continuer':'Étudier'}<ArrowRight className="size-4"/></Button></div></div></article>}
function Metric({icon:Icon,label,value}:{icon:typeof Coins;label:string;value:string}){return <div className="rounded-lg bg-slate-50 p-2"><Icon className="size-3.5 text-blue-500"/><p className="mt-1 text-slate-400">{label}</p><p className="truncate font-bold text-slate-800" title={value}>{value}</p></div>}
