import { zodResolver } from '@hookform/resolvers/zod'
import { ArrowLeft, ArrowRight, Save } from 'lucide-react'
import { useEffect, useState } from 'react'
import { FormProvider, useForm, type Resolver } from 'react-hook-form'
import { useNavigate, useParams } from 'react-router-dom'
import { toast } from 'sonner'
import { PageHeader } from '../../../components/common/PageHeader'
import { Button } from '../../../components/ui/Button'
import { LoadingSkeleton } from '../../../components/ui/LoadingSkeleton'
import { MarketStudyStepper } from '../components/wizard/MarketStudyStepper'
import { CommercialScoresStep, CompetitorsStep, GeneralInformationStep, MarketDataStep, MarketStudyReviewStep, PricingProfitabilityStep, RisksStep, SalesForecastStep, TargetCustomersStep } from '../components/wizard/StudySteps'
import { useCommercialProduct } from '../hooks/useCommercialProducts'
import { useMarketStudyMutations } from '../hooks/useMarketStudies'
import { defaultStudyInput } from '../mocks/marketStudies.mock'
import { marketStudySchema, type MarketStudyFormValues } from '../schemas/marketStudySchema'
import type { MarketStudyInput } from '../types/commercial.types'
const fieldGroups:(keyof MarketStudyInput)[][]=[['studyName','targetMarket','geographicArea','customerSegment','studyDate','managerName'],['estimatedMarketSize','annualGrowthRate','demandLevel','marketTrend','distributionChannels','commercializationArea'],['customerType','ageRange','purchasingPower','consumptionHabits','purchaseFrequency','preferences','priceSensitivity'],['competitors'],['pricing'],['forecast'],['risks'],['scores'],[]]
const components=[GeneralInformationStep,MarketDataStep,TargetCustomersStep,CompetitorsStep,PricingProfitabilityStep,SalesForecastStep,RisksStep,CommercialScoresStep,MarketStudyReviewStep]
export function MarketStudyWizardPage(){const{productId=''}=useParams(),product=useCommercialProduct(productId),navigate=useNavigate(),{save}=useMarketStudyMutations();const[current,setCurrent]=useState(0),[ready,setReady]=useState(false);const methods=useForm<MarketStudyFormValues>({resolver:zodResolver(marketStudySchema) as Resolver<MarketStudyFormValues>,defaultValues:defaultStudyInput()});useEffect(()=>{if(product.data&&!ready){const v=product.data;const initial=v.study??defaultStudyInput(v.product.id,v.product.version,v.productionCost,v.product.targetSalePrice);const local=localStorage.getItem(`commercial-study-${productId}`);methods.reset(local?JSON.parse(local) as MarketStudyFormValues:initial);setReady(true)}},[product.data,productId,ready,methods]);if(product.isLoading)return <LoadingSkeleton lines={9}/>;const StepComponent=components[current]??MarketStudyReviewStep;const next=async()=>{const valid=await methods.trigger(fieldGroups[current]);if(valid)setCurrent(v=>Math.min(8,v+1));else toast.error('Complétez les champs requis avant de continuer.')};const persist=()=>{localStorage.setItem(`commercial-study-${productId}`,JSON.stringify(methods.getValues()));toast.success('Brouillon sauvegardé localement.')};const submit=methods.handleSubmit(input=>save.mutate({input,status:'Completed',id:product.data?.study?.id},{onSuccess:study=>{localStorage.removeItem(`commercial-study-${productId}`);toast.success('Étude calculée.');navigate(`/commercial/studies/${study.id}/result`)},onError:e=>toast.error(e.message)}));return <div className="space-y-6"><PageHeader eyebrow="Assistant d’étude" title={product.data?.product.name??'Étude de marché'} description="Parcours guidé avec validation progressive et sauvegarde locale simulée." actions={<Button variant="secondary" onClick={persist}><Save className="size-4"/>Sauvegarder</Button>}/><MarketStudyStepper current={current} onSelect={setCurrent}/><FormProvider {...methods}><form onSubmit={submit}><StepComponent/><div className="mt-5 flex justify-between"><Button type="button" variant="secondary" disabled={current===0} onClick={()=>setCurrent(v=>Math.max(0,v-1))}><ArrowLeft className="size-4"/>Précédent</Button>{current<8?<Button type="button" onClick={next}>Suivant<ArrowRight className="size-4"/></Button>:<Button type="submit" loading={save.isPending}>Calculer la faisabilité</Button>}</div></form></FormProvider></div>}
