import { BarChart3, Pencil } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { PageHeader } from '../../../components/common/PageHeader'
import { StatusBadge } from '../../../components/common/StatusBadge'
import { Button } from '../../../components/ui/Button'
import { ErrorState } from '../../../components/ui/ErrorState'
import { LoadingSkeleton } from '../../../components/ui/LoadingSkeleton'
import { useMarketStudy } from '../hooks/useMarketStudies'
import { formatCurrency, formatProductionDate } from '../../production/utils/productionFormatters'
export function MarketStudyDetailsPage(){const{studyId=''}=useParams();const q=useMarketStudy(studyId);if(q.isLoading)return <LoadingSkeleton lines={7}/>;const s=q.data;if(!s)return <ErrorState title="Étude introuvable" description="L’étude demandée n’existe pas."/>;return <div className="space-y-6"><PageHeader eyebrow={`Produit ${s.productId} · v${s.productVersion}`} title={s.studyName} description={`Mise à jour ${formatProductionDate(s.updatedAt)} par ${s.managerName}`} actions={<><StatusBadge label={s.status} tone={s.status==='Validated'?'success':'info'}/><Link to={`/commercial/products/${s.productId}/market-study`}><Button variant="secondary"><Pencil className="size-4"/>Modifier</Button></Link>{s.feasibility&&<Link to={`/commercial/studies/${s.id}/result`}><Button><BarChart3 className="size-4"/>Voir le résultat</Button></Link>}</>}/><div className="grid gap-5 lg:grid-cols-2"><Section title="Marché"><Info label="Marché cible" value={s.targetMarket}/><Info label="Zone" value={s.geographicArea}/><Info label="Demande" value={s.demandLevel}/><Info label="Croissance" value={`${s.annualGrowthRate}%`}/></Section><Section title="Rentabilité"><Info label="Prix proposé" value={formatCurrency(s.pricing.proposedSalePrice)}/><Info label="Coût total" value={formatCurrency(s.pricing.totalEstimatedCost)}/><Info label="Marge" value={`${s.pricing.marginRate.toFixed(1)}%`}/><Info label="CA annuel" value={formatCurrency(s.forecast.annualRevenue)}/></Section><Section title="Concurrence"><Info label="Concurrents analysés" value={String(s.competitors.length)}/><Info label="Prix moyen marché" value={formatCurrency(s.pricing.averageMarketPrice)}/></Section><Section title="Risques"><Info label="Risques identifiés" value={String(s.risks.length)}/><Info label="Risque maximal" value={String(Math.max(0,...s.risks.map(r=>r.probability*r.impact)))}/></Section></div></div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="surface-card p-5"><h2 className="mb-4 font-bold">{title}</h2><dl className="grid grid-cols-2 gap-4">{children}</dl></section>};function Info({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-slate-400">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>}
