import { z } from 'zod'
import { DEMAND_LEVELS, MARKET_TRENDS, RISK_TYPES } from '../types/commercial.types'
const score = z.coerce.number().min(0).max(100)
const competitor = z.object({ id:z.string(),competitorName:z.string().min(2),productName:z.string().min(2),price:z.coerce.number().min(0),quantity:z.coerce.number().positive(),estimatedQuality:score,marketShare:score,strengths:z.string(),weaknesses:z.string(),salesChannels:z.string(),customerRating:z.coerce.number().min(0).max(5),imageUrl:z.string().nullable() })
const risk = z.object({ id:z.string(),riskType:z.enum(RISK_TYPES),probability:z.coerce.number().int().min(1).max(5),impact:z.coerce.number().int().min(1).max(5),description:z.string().min(4),mitigationAction:z.string().min(4) })
export const marketStudySchema=z.object({
  studyName:z.string().min(3,'Le nom de l’étude est obligatoire.'),productId:z.string().min(1),productVersion:z.coerce.number().positive(),targetMarket:z.string().min(2),geographicArea:z.string().min(2),customerSegment:z.string().min(2),studyDate:z.string().min(1),managerName:z.string().min(2),
  estimatedMarketSize:z.coerce.number().positive(),annualGrowthRate:z.coerce.number().min(-100).max(500),demandLevel:z.enum(DEMAND_LEVELS),marketTrend:z.enum(MARKET_TRENDS),seasonality:z.string(),distributionChannels:z.string().min(2),commercializationArea:z.string().min(2),
  customerType:z.string().min(2),ageRange:z.string(),purchasingPower:z.string(),consumptionHabits:z.string(),purchaseFrequency:z.string(),preferences:z.string(),priceSensitivity:score,
  competitors:z.array(competitor),pricing:z.object({productionCost:z.coerce.number().min(0),proposedSalePrice:z.coerce.number().positive(),averageMarketPrice:z.coerce.number().positive(),minimumAcceptablePrice:z.coerce.number().min(0),maximumAcceptablePrice:z.coerce.number().positive(),desiredMargin:z.coerce.number().min(0),calculatedMargin:z.coerce.number(),marginRate:z.coerce.number(),estimatedMarketingCost:z.coerce.number().min(0),estimatedDistributionCost:z.coerce.number().min(0),estimatedCommission:z.coerce.number().min(0),totalEstimatedCost:z.coerce.number().min(0),breakEvenUnits:z.coerce.number().min(0)}),
  forecast:z.object({monthlySalesVolume:z.coerce.number().min(0),annualSalesVolume:z.coerce.number().min(0),monthlyRevenue:z.coerce.number().min(0),annualRevenue:z.coerce.number().min(0),breakEvenPeriodMonths:z.coerce.number().min(0),expectedGrowthRate:z.coerce.number().min(-100).max(500)}),risks:z.array(risk),scores:z.object({demandPotentialScore:score,pricePositioningScore:score,competitiveAdvantageScore:score,distributionScore:score,productAttractivenessScore:score,profitabilityScore:score,commercialRiskScore:score,marketFitScore:score})
})
export type MarketStudyFormValues=z.infer<typeof marketStudySchema>
